title: Anthony Tucker # your name (or website title) here
logo: "/images/AvatarMaker (4).png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  I am a 9th grader at Bishop Amat High School
  <br><br>
  Second description 
  <br><br>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
